### PR TITLE
added support for changing the location of the .git root

### PR DESCRIPTION
**Pull request by jv-dan**

### CODE REVIEW

**Comment by calavera** [comment]
Hi @jv-dan, thanks for your contribution!

I understand that this solves your problem, but I'm not completely sure if it's the right way to fix this issue. You can see the discussion in #64 

I'm totally open to suggestions though, I might be wrong and this might be the right solution for the future.

**Comment by jv-dan** [comment]
Interesting. Looks like two separate, yet very related issues that may in fact be both solved by being able to specify the git root explicitly. My use-case was for being able to run tests and report on them when the ACTUAL, not a dummy app, doesn't live in the root of the git repository. I'll keep an eye on the discussion and see what others have to say!

**Comment by jv-dan** [comment]
Sorry for holding up the release!

**Comment by calavera** [comment]
:cool: thanks @jv-dan. Merging!

**Pull request merged**
