### PR TITLE
Do not format coverage result when exiting forked process

### PR DESCRIPTION
**Pull request by JacobNinja**
Before: Every forked process will attempt to send coverage results
```
cc:analyzer jacob$ CODECLIMATE_REPO_TOKEN=xxx bundle exec rake spec:integration
I, [2015-04-28T10:30:01.530853 #86241]  INFO -- : Reporting coverage data to Code Climate.
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
Coverage = 13.46%. Coverage = 13.08%. Sending report to https://codeclimate.com for branch jr-disable_language... Sending report to https://codeclimate.com for branch jr-disable_language... Code Climate encountered an exception: RuntimeError
HTTP Error: 401
```

After:
```
cc:analyzer jacob$ CODECLIMATE_REPO_TOKEN=xxx bundle exec rake spec:integration
I, [2015-04-28T10:30:56.158738 #86317]  INFO -- : Reporting coverage data to Code Climate.
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
.....

Finished in 45.41 seconds
5 examples, 0 failures
Coverage = 64.19%. Sending report to https://codeclimate.com for branch jr-disable_language... Code Climate encountered an exception: RuntimeError
HTTP Error: 401
```

### CODE REVIEW

**Comment by noahd1** [comment]
Interesting. Does the master test coverage process have the coverage data of all the sub-processes/children?

**Comment by JacobNinja** [comment]
@noahd1 nope that data is discarded. forked processes use "copy on write" so shared memory cannot be written to directly.

It's possible to write the forked results to disk (or pipe) and collect them before formatting the total result.

**Comment by noahd1** [comment]
Right, so it'll be an incomplete test coverage report. We just need to implement support for multiple POSTs (which we're working on)

**Comment by JacobNinja** [comment]
@noahd1 the problem occurs because of multiple POST payloads. The test suite becomes unstable and crashes frequently

**Comment by brynary** [comment]
@noahd1 said we should close this for now, because of concerns around the implementation and also lack of priority.

**Pull request closed without merging**
