### PR TITLE
WIP: New usage and addition fixes

### PR DESCRIPTION
**Pull request by pbrisbin**
This is based off of #121. I have a few nits I want to address in that before
prepping the release, which I'll do here. First thing is to use the new usage
ourselves and report coverage with ourselves as a form of integration test.

/cc @mrb

### CODE REVIEW

**Comment by pbrisbin** [comment]
@mrb do you plan to merge this directly or into #121?

**Comment by pbrisbin** [comment]
I'm thinking, you should just merge this into #121, get it green, then I'll review it there.

**Comment by mrb** [comment]
@pbrisbin Okey dokey sounds good!

**Comment by pbrisbin** [comment]
Closing in favor of #121

**Pull request closed without merging**
