### PR TITLE
Support GitLab CI

### PR DESCRIPTION
**Pull request by hiroponz**
See http://doc.gitlab.com/ci/variables/README.html

### CODE REVIEW

**Comment by GordonDiggs** [comment]
@hiroponz can you confirm that `env['CI_BUILD_REF_NAME']` is `master` when built on the master branch?

**Comment by hiroponz** [comment]
@GordonDiggs Yes I have already confirmed that by using my forked gem. I could send the coverage report of ruby from GitLab CI.

**Comment by GordonDiggs** [comment]
Awesome thank you!

**Comment by hiroponz** [comment]
Thanks :)

**Comment by hiroponz** [comment]
@GordonDiggs Can you tell me that codeclimate will support an [GitLab](https://gitlab.com) Open Source repository?

**Pull request merged**
