### PR TITLE
merge all reports into 1 before submitting

### PR DESCRIPTION
**Pull request by grosser**
we are using https://travis-ci.org/grosser/forking_test_runner to run our tests -> 200+ coverage reports per server -> unify them before sending or we run into a 413 Request entity too large

this includes my last PR, let's dicuss/merge that first

also needed for [cc-amend](https://github.com/grosser/cc-amend) which combines reports from multiple servers into one
@calavera

### CODE REVIEW

**Comment by grosser** [comment]
@noahd1 can you review this plz, getting rid of a whole endpoint on cc-side + sending less data should be a nice win :)

**Comment by grosser** [comment]
@noahd1 can you review this / anyone else I should ping ?

**Comment by grosser** [comment]
@noahd1 could you plz review this ?

**Comment by grosser** [comment]
@noahd1 can you review plz ?

**Comment by noahd1** [comment]
Hi @grosser.

Sorry it's taken me some time to get to this. My expectation, based on how our backend works is that this actually wouldn't work unfortunately. Are you saying you've tested this approach and it works?

**Comment by grosser** [comment]
I submitted coverage for this project with it: https://codeclimate.com/github/grosser/cc-amend/code via https://github.com/grosser/cc-amend/blob/master/Rakefile which is a little simplistic, I'll make it more complex to see if I run into any new issues (atm it just merged the same report 3 times).

Can you elaborate why it would not work / how I can fix that ?

**Comment by grosser** [comment]
[Tried it](https://github.com/grosser/cc-amend/commit/ca88697f408f880b1d9418af651f21f9e62135d8), works just fine: https://codeclimate.com/github/grosser/cc-amend/CoverMe "Source" tab, foo and bar methods are from different reports and are both marked covered by joining those 2 reports.

**Comment by grosser** [comment]
@noahd1 added another test to also report in different files and still works fine, so please let me know what you think would not work

**Comment by noahd1** [comment]
Hi @grosser. Sorry for the long cycle time in responses here -- we had a conference and wear multiple hats here. The good news with this stuff is that if you find a solution that works for you, you do not need to wait until code is reviewed or merged into the mainline.

In this case, unfortunately, it's not a matter of your code inasmuch as its server-side support. The batch results endpoint was written for a specific integration and has other undocumented requirements. It wasn't intended for general consumption. I'm sorry if you spent time on this -- I've updated the source code with a comment to reflect this limitation.

I'm fully aware that customers really want first class support for parallel test runs, and sorry it doesn't yet exist. The solution that we'd lean towards would probably be multiple API calls, since that general solution would also work across multiple machines. It's in our roadmap, but not sure exactly when we'll get to it.

**Comment by grosser** [comment]
how about making this logic a class like `ReportMerger` so I can use that and then `post_results` ?
(trying to not make my own gem / make cc-amend plug and play and share the knowledge of report merging)

You could avoid all kinds of engineering efforts on your side by simply hosting a cc-amend server :)
(maybe document as alpha service or something like that, still better than making users run their own server / send their data through some 3rd party heroku instance)

**Comment by noahd1** [comment]
Unfortunately even alpha and beta services require support and infrastructure -- we'll get to a better solution here, but only when we feel confident we can roll it out to customers in a sustainable and maintainable way. For now -- if you can get it working with a separate gem to aggregate results that might be the simplest/quickest path forward for you.

**Comment by grosser** [comment]
Can we keep the logic inside here/document it (just as a class that is not
used/loaded by default) so it's more obvious and maybe it helps more ppl ?
It's not only useful when you have multiple servers reporting things, but
also when 1 server generates multiple files locally.

**Comment by grosser** [comment]
converted everything into a standalone gem: https://github.com/grosser/codeclimate_batch

**Pull request closed without merging**
