### PR TITLE
Cut 1.0.0

### PR DESCRIPTION
**Pull request by maxjacobson**
Re-opening of #137 after confirming master is good to release

### CODE REVIEW

**Comment by romaintb** [comment]
since the update, we get : 
`LoadError: cannot load such file -- simplecov`

can it be related to the 1.0.0 release ?

**Comment by romaintb** [comment]
ok, readme states we have to require it manually. alright

**Comment by maxjacobson** [comment]
Yep, sorry about the confusion! https://github.com/codeclimate/ruby-test-reporter/pull/139 just updated the README instructions to help make it more clear.

**Comment by romaintb** [comment]
@maxjacobson yeah, sorry for posting before reading README :)

**Pull request merged**
